# Generated by Django 5.2.3 on 2025-06-21 09:31

import core.services.service_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredservice',
            name='description',
        ),
        migrations.AlterField(
            model_name='registeredservice',
            name='service_type',
            field=models.CharField(choices=core.services.service_registry.ServiceDefinitions.choices, max_length=50),
        ),
    ]
