# Generated by Django 5.2.3 on 2025-07-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_registeredservice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('type', models.CharField(choices=[('HEALTHCHECK', 0), ('ENHANCED_CALL', 1)], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.registeredservice')),
            ],
        ),
    ]
