# Generated by Django 5.2.3 on 2025-08-20 16:47

import django.db.models.deletion
import user_services.registry.service_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=user_services.registry.service_registry.ServiceDefinitions.choices, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('type', models.CharField(choices=[('HEALTHCHECK', 'health check'), ('ENHANCED_CALL', 'enhanced call')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_services.registeredservice')),
            ],
        ),
    ]
